settings:
  title: 'Status Page'
  url: 'https://status.reflow.ai' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: app-reflow-prod # unique identifier
    name: reflow.ai
    description: 'Reflow Production Web APP' # default=empty
    url: 'https://reflow.ai' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  
  - id: app-reflow-staging # unique identifier
    name: staging.reflow.ai
    description: 'Reflow Staging Web APP' # default=empty
    url: 'https://staging.reflow.ai' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: app-reflow-analytics-prod # unique identifier
    name: analytics.reflow.ai
    description: 'Reflow Production Analytics Web APP' # default=empty
    url: 'https://analytics.reflow.ai' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ai-service-reflow-prod # unique identifier
    name: ai-service.reflow.ai
    description: 'AI Service production env' # default=empty
    url: 'https://ai-service.reflow.ai/swagger-ui' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id:  ai-service-reflow-staging # unique identifier
    name: ai-service-staging.reflow.ai
    description: 'AI Service production staging' # default=empty
    url: 'https://ai-service-staging.reflow.ai/swagger-ui' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true